import { Inter } from "next/font/google";
import "./globals.css";
import UiNextProvider from "@/lib/UiNextProvider";
import AuthProvider from "@/SessionProvider";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
    className={(inter.className, "dark")}
    style={{
      colorScheme: "dark",
    }}
    lang="en">
      <body>
        <AuthProvider>
        <UiNextProvider>
        {children}
        </UiNextProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
